{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6cc327ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "============================================================\n",
    "  VISUALIZATIONS MODULE\n",
    "  Saare graphs aur charts yahan hain\n",
    "============================================================\n",
    "\"\"\"\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import seaborn as sns\n",
    "from matplotlib.gridspec import GridSpec\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ── Custom Dark Theme Colors ──────────────────────────────\n",
    "PALETTE    = ['#6C63FF', '#FF6B6B', '#48CAE4', '#06D6A0', '#FFD166', '#EF476F']\n",
    "BG_COLOR   = '#0F0F1A'\n",
    "CARD_COLOR = '#1A1A2E'\n",
    "TEXT_COLOR = '#E0E0FF'\n",
    "\n",
    "\n",
    "def set_dark_style():\n",
    "    \"\"\"Saare charts ke liye dark theme set karo.\"\"\"\n",
    "    plt.rcParams.update({\n",
    "        'figure.facecolor' : BG_COLOR,\n",
    "        'axes.facecolor'   : CARD_COLOR,\n",
    "        'axes.edgecolor'   : '#2D2D4E',\n",
    "        'axes.labelcolor'  : TEXT_COLOR,\n",
    "        'xtick.color'      : TEXT_COLOR,\n",
    "        'ytick.color'      : TEXT_COLOR,\n",
    "        'text.color'       : TEXT_COLOR,\n",
    "        'grid.color'       : '#2D2D4E',\n",
    "        'grid.alpha'       : 0.5,\n",
    "        'font.family'      : 'DejaVu Sans',\n",
    "        'axes.titlesize'   : 13,\n",
    "        'axes.titleweight' : 'bold',\n",
    "    })\n",
    "\n",
    "\n",
    "def plot_rating_distribution(ratings, save_path=None):\n",
    "    \"\"\"Rating distribution ka histogram.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "    fig.suptitle('⭐ Rating Analysis Dashboard',\n",
    "                 fontsize=16, fontweight='bold', color=TEXT_COLOR, y=1.02)\n",
    "\n",
    "    # Plot 1: Rating Distribution\n",
    "    ax1 = axes[0]\n",
    "    rating_counts = ratings['rating'].value_counts().sort_index()\n",
    "    bars = ax1.bar(\n",
    "        rating_counts.index, rating_counts.values,\n",
    "        color=PALETTE[:len(rating_counts)],\n",
    "        edgecolor='white', linewidth=0.5, width=0.35\n",
    "    )\n",
    "    ax1.set_title('Distribution of Ratings')\n",
    "    ax1.set_xlabel('Rating Value')\n",
    "    ax1.set_ylabel('Number of Ratings')\n",
    "    ax1.grid(axis='y', alpha=0.3)\n",
    "    for bar, val in zip(bars, rating_counts.values):\n",
    "        ax1.text(\n",
    "            bar.get_x() + bar.get_width() / 2,\n",
    "            bar.get_height() + 50,\n",
    "            f'{val:,}', ha='center', va='bottom',\n",
    "            fontsize=9, color=TEXT_COLOR\n",
    "        )\n",
    "\n",
    "    # Plot 2: Ratings per User\n",
    "    ax2 = axes[1]\n",
    "    ratings_per_user = ratings.groupby('userId')['rating'].count()\n",
    "    ax2.hist(ratings_per_user, bins=40,\n",
    "             color=PALETTE[2], edgecolor='white', linewidth=0.3, alpha=0.85)\n",
    "    ax2.set_title('Ratings per User (Activity Distribution)')\n",
    "    ax2.set_xlabel('Number of Ratings by User')\n",
    "    ax2.set_ylabel('Number of Users')\n",
    "    ax2.axvline(\n",
    "        ratings_per_user.mean(), color=PALETTE[1],\n",
    "        linestyle='--', linewidth=2,\n",
    "        label=f'Mean = {ratings_per_user.mean():.1f}'\n",
    "    )\n",
    "    ax2.legend(facecolor=CARD_COLOR, edgecolor='gray')\n",
    "    ax2.grid(axis='y', alpha=0.3)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig\n",
    "\n",
    "\n",
    "def plot_genre_analysis(movies, save_path=None):\n",
    "    \"\"\"Genre popularity analysis.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
    "    fig.suptitle('🎬 Genre Analysis',\n",
    "                 fontsize=16, fontweight='bold', color=TEXT_COLOR)\n",
    "\n",
    "    # Parse genres\n",
    "    all_genres = []\n",
    "    for genres in movies['genres'].dropna():\n",
    "        all_genres.extend(genres.split('|'))\n",
    "    genre_counts = pd.Series(all_genres).value_counts()\n",
    "\n",
    "    # Plot 1: Horizontal Bar Chart\n",
    "    ax1 = axes[0]\n",
    "    top_genres = genre_counts.head(12)\n",
    "    colors     = plt.cm.plasma(np.linspace(0.2, 0.9, len(top_genres)))\n",
    "    bars       = ax1.barh(range(len(top_genres)), top_genres.values, color=colors)\n",
    "    ax1.set_yticks(range(len(top_genres)))\n",
    "    ax1.set_yticklabels(top_genres.index, fontsize=10)\n",
    "    ax1.set_title('Top Genres by Movie Count')\n",
    "    ax1.set_xlabel('Number of Movies')\n",
    "    ax1.invert_yaxis()\n",
    "    for bar, val in zip(bars, top_genres.values):\n",
    "        ax1.text(val + 2, bar.get_y() + bar.get_height() / 2,\n",
    "                 str(val), va='center', fontsize=9, color=TEXT_COLOR)\n",
    "\n",
    "    # Plot 2: Pie Chart\n",
    "    ax2 = axes[1]\n",
    "    top8 = genre_counts.head(8)\n",
    "    wedges, texts, autotexts = ax2.pie(\n",
    "        top8.values, labels=top8.index, autopct='%1.1f%%',\n",
    "        colors=PALETTE * 2, startangle=140,\n",
    "        textprops={'color': TEXT_COLOR, 'fontsize': 9}\n",
    "    )\n",
    "    for at in autotexts:\n",
    "        at.set_color(BG_COLOR)\n",
    "        at.set_fontweight('bold')\n",
    "    ax2.set_title('Genre Distribution (Pie)')\n",
    "    ax2.set_facecolor(CARD_COLOR)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig\n",
    "\n",
    "\n",
    "def plot_similarity_heatmap(sim_matrix, title='Cosine Similarity Heatmap',\n",
    "                             save_path=None):\n",
    "    \"\"\"Movie similarity matrix heatmap.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig, ax = plt.subplots(figsize=(14, 11))\n",
    "\n",
    "    n          = min(20, len(sim_matrix))\n",
    "    sub_matrix = sim_matrix.iloc[:n, :n]\n",
    "    labels     = [t[:25] + '…' if len(t) > 25 else t\n",
    "                  for t in sub_matrix.index]\n",
    "\n",
    "    sns.heatmap(\n",
    "        sub_matrix, ax=ax,\n",
    "        cmap='RdYlGn', vmin=0, vmax=1,\n",
    "        xticklabels=labels, yticklabels=labels,\n",
    "        annot=False, linewidths=0.3, linecolor='#0F0F1A',\n",
    "        cbar_kws={'label': 'Cosine Similarity Score', 'shrink': 0.8}\n",
    "    )\n",
    "    ax.set_title(f'🔥 {title}\\n(Higher value = More Similar)',\n",
    "                 fontsize=14, pad=20, color=TEXT_COLOR)\n",
    "    plt.xticks(rotation=45, ha='right', fontsize=7)\n",
    "    plt.yticks(rotation=0, fontsize=7)\n",
    "\n",
    "    cbar = ax.collections[0].colorbar\n",
    "    cbar.ax.yaxis.label.set_color(TEXT_COLOR)\n",
    "    cbar.ax.tick_params(colors=TEXT_COLOR)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig\n",
    "\n",
    "\n",
    "def plot_recommendation_comparison(cb_recs, cf_recs, movie_title,\n",
    "                                    save_path=None):\n",
    "    \"\"\"Content-Based vs Collaborative recommendations comparison.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n",
    "    fig.suptitle(f'🤖 Recommendations for: \"{movie_title}\"',\n",
    "                 fontsize=14, fontweight='bold', color=TEXT_COLOR)\n",
    "\n",
    "    datasets = [\n",
    "        (cb_recs, axes[0], PALETTE[0], 'Content-Based',  'similarity_score'),\n",
    "        (cf_recs, axes[1], PALETTE[1], 'Collaborative',  'similarity_score'),\n",
    "    ]\n",
    "\n",
    "    for df, ax, color, label, score_col in datasets:\n",
    "        if df is None or df.empty or score_col not in df.columns:\n",
    "            ax.text(0.5, 0.5, 'No data', transform=ax.transAxes,\n",
    "                    ha='center', color=TEXT_COLOR)\n",
    "            ax.set_title(label)\n",
    "            continue\n",
    "\n",
    "        top          = df.head(8).copy()\n",
    "        short_titles = [t[:30] + '…' if len(t) > 30 else t\n",
    "                        for t in top['title']]\n",
    "        scores       = top[score_col].values\n",
    "\n",
    "        bars = ax.barh(range(len(short_titles)), scores,\n",
    "                       color=[color] * len(scores),\n",
    "                       edgecolor='white', linewidth=0.4, alpha=0.9)\n",
    "        ax.set_yticks(range(len(short_titles)))\n",
    "        ax.set_yticklabels(short_titles, fontsize=9)\n",
    "        ax.set_xlim(0, max(scores) * 1.2 if len(scores) > 0 else 1)\n",
    "        ax.set_xlabel('Similarity Score')\n",
    "        ax.set_title(f'{label} Filtering', fontsize=12)\n",
    "        ax.invert_yaxis()\n",
    "        ax.grid(axis='x', alpha=0.3)\n",
    "\n",
    "        for bar, val in zip(bars, scores):\n",
    "            ax.text(val + 0.005,\n",
    "                    bar.get_y() + bar.get_height() / 2,\n",
    "                    f'{val:.3f}', va='center',\n",
    "                    fontsize=8, color=TEXT_COLOR)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig\n",
    "\n",
    "\n",
    "def plot_evaluation_metrics(metrics, save_path=None):\n",
    "    \"\"\"Evaluation metrics dashboard.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig = plt.figure(figsize=(14, 6))\n",
    "    gs  = GridSpec(1, 3, figure=fig, wspace=0.4)\n",
    "    fig.suptitle('📊 Model Evaluation Metrics',\n",
    "                 fontsize=16, fontweight='bold', color=TEXT_COLOR)\n",
    "\n",
    "    metric_configs = [\n",
    "        ('RMSE',        metrics.get('RMSE', 0),        1.0, 'Lower is Better',  PALETTE[1]),\n",
    "        ('MAE',         metrics.get('MAE', 0),          1.0, 'Lower is Better',  PALETTE[2]),\n",
    "        ('Precision@K', metrics.get('Precision@K', 0), 1.0, 'Higher is Better', PALETTE[0]),\n",
    "    ]\n",
    "\n",
    "    for i, (name, value, max_val, note, color) in enumerate(metric_configs):\n",
    "        ax     = fig.add_subplot(gs[0, i])\n",
    "        sizes  = [value / max_val, 1 - value / max_val]\n",
    "        colors_donut = [color, '#2D2D4E']\n",
    "\n",
    "        ax.pie(sizes, colors=colors_donut, startangle=90,\n",
    "               wedgeprops=dict(width=0.4, edgecolor=BG_COLOR))\n",
    "\n",
    "        ax.text(0,  0.10, f'{value:.4f}', ha='center', va='center',\n",
    "                fontsize=20, fontweight='bold', color=color)\n",
    "        ax.text(0, -0.25, name,  ha='center', va='center',\n",
    "                fontsize=13, fontweight='bold', color=TEXT_COLOR)\n",
    "        ax.text(0, -0.50, note,  ha='center', va='center',\n",
    "                fontsize=9,  color='#888', style='italic')\n",
    "        ax.set_facecolor(CARD_COLOR)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig\n",
    "\n",
    "\n",
    "def plot_popularity_vs_ratings(movies, save_path=None):\n",
    "    \"\"\"Average rating vs popularity scatter plot.\"\"\"\n",
    "    set_dark_style()\n",
    "    fig, ax = plt.subplots(figsize=(12, 7))\n",
    "\n",
    "    all_genres = []\n",
    "    for g in movies['genres'].dropna():\n",
    "        all_genres.append(g.split('|')[0])\n",
    "\n",
    "    movies = movies.copy()\n",
    "    movies['primary_genre'] = all_genres\n",
    "\n",
    "    top_genres   = movies['primary_genre'].value_counts().head(6).index\n",
    "    genre_colors = {g: PALETTE[i] for i, g in enumerate(top_genres)}\n",
    "\n",
    "    for genre in top_genres:\n",
    "        subset = movies[movies['primary_genre'] == genre]\n",
    "        ax.scatter(\n",
    "            subset['avg_rating'], subset['rating_count'],\n",
    "            label=genre, color=genre_colors[genre],\n",
    "            alpha=0.7, s=40, edgecolors='white', linewidth=0.3\n",
    "        )\n",
    "\n",
    "    others = movies[~movies['primary_genre'].isin(top_genres)]\n",
    "    ax.scatter(others['avg_rating'], others['rating_count'],\n",
    "               label='Other', color='#555', alpha=0.4, s=20)\n",
    "\n",
    "    ax.set_xlabel('Average Rating', fontsize=12)\n",
    "    ax.set_ylabel('Number of Ratings (Popularity)', fontsize=12)\n",
    "    ax.set_title('🌟 Popularity vs Average Rating by Genre',\n",
    "                 fontsize=14, pad=15)\n",
    "    ax.legend(facecolor=CARD_COLOR, edgecolor='gray',\n",
    "              framealpha=0.8, fontsize=9)\n",
    "    ax.grid(alpha=0.3)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=BG_COLOR)\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2cb2024b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
