{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2081af31",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'models'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 16\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mos\u001b[39;00m\n\u001b[0;32m     15\u001b[0m sys\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39minsert(\u001b[38;5;241m0\u001b[39m, os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mabspath(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m'\u001b[39m))\n\u001b[1;32m---> 16\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mmodels\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mrecommender\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     17\u001b[0m     load_movielens_data, preprocess_data,\n\u001b[0;32m     18\u001b[0m     ContentBasedRecommender, CollaborativeFilteringRecommender,\n\u001b[0;32m     19\u001b[0m     HybridRecommender, evaluate_model\n\u001b[0;32m     20\u001b[0m )\n\u001b[0;32m     21\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mvisualizations\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     22\u001b[0m     plot_rating_distribution, plot_genre_analysis,\n\u001b[0;32m     23\u001b[0m     plot_similarity_heatmap, plot_recommendation_comparison,\n\u001b[0;32m     24\u001b[0m     plot_evaluation_metrics, plot_popularity_vs_ratings\n\u001b[0;32m     25\u001b[0m )\n\u001b[0;32m     27\u001b[0m \u001b[38;5;66;03m# ─────────────────────────────────────────────\u001b[39;00m\n\u001b[0;32m     28\u001b[0m \u001b[38;5;66;03m#  PAGE CONFIG\u001b[39;00m\n\u001b[0;32m     29\u001b[0m \u001b[38;5;66;03m# ─────────────────────────────────────────────\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'models'"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "============================================================\n",
    "  STREAMLIT WEB APP - Product Recommendation System\n",
    "  Run with: streamlit run app.py\n",
    "============================================================\n",
    "\"\"\"\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import sys\n",
    "import os\n",
    "\n",
    "sys.path.insert(0, os.path.abspath('.'))\n",
    "from models.recommender import (\n",
    "    load_movielens_data, preprocess_data,\n",
    "    ContentBasedRecommender, CollaborativeFilteringRecommender,\n",
    "    HybridRecommender, evaluate_model\n",
    ")\n",
    "from utils.visualizations import (\n",
    "    plot_rating_distribution, plot_genre_analysis,\n",
    "    plot_similarity_heatmap, plot_recommendation_comparison,\n",
    "    plot_evaluation_metrics, plot_popularity_vs_ratings\n",
    ")\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  PAGE CONFIG\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title = \"🎬 RecoAI – Movie Recommendation System\",\n",
    "    page_icon  = \"🎬\",\n",
    "    layout     = \"wide\",\n",
    "    initial_sidebar_state = \"expanded\"\n",
    ")\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  CUSTOM CSS\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "  :root {\n",
    "    --bg-primary  : #0D0D1F;\n",
    "    --bg-card     : #141428;\n",
    "    --bg-card2    : #1A1A35;\n",
    "    --accent-blue : #6C63FF;\n",
    "    --accent-pink : #FF6B9D;\n",
    "    --accent-cyan : #48CAE4;\n",
    "    --accent-green: #06D6A0;\n",
    "    --text-primary: #E8E8FF;\n",
    "    --text-muted  : #9090B0;\n",
    "    --border      : #2A2A4A;\n",
    "    --radius      : 12px;\n",
    "  }\n",
    "\n",
    "  .stApp { background: var(--bg-primary) !important; }\n",
    "  html, body, [class*=\"css\"] { color: var(--text-primary) !important; }\n",
    "\n",
    "  .hero-header {\n",
    "    background: linear-gradient(135deg, #1A0533 0%, #0D1B4D 50%, #0A2B2B 100%);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: var(--radius);\n",
    "    padding: 2.5rem 3rem;\n",
    "    margin-bottom: 2rem;\n",
    "    text-align: center;\n",
    "    position: relative;\n",
    "    overflow: hidden;\n",
    "  }\n",
    "  .hero-title {\n",
    "    font-size: 2.8rem; font-weight: 800;\n",
    "    background: linear-gradient(135deg, #A78BFA, #60A5FA, #34D399);\n",
    "    -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n",
    "    margin: 0 0 0.5rem 0;\n",
    "  }\n",
    "  .hero-subtitle { font-size: 1rem; color: var(--text-muted); margin: 0; }\n",
    "\n",
    "  .metric-row { display: flex; gap: 1rem; margin: 1.5rem 0; flex-wrap: wrap; }\n",
    "  .metric-card {\n",
    "    flex: 1; min-width: 140px;\n",
    "    background: var(--bg-card);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: var(--radius);\n",
    "    padding: 1.2rem 1rem; text-align: center;\n",
    "    transition: transform 0.2s, border-color 0.2s;\n",
    "  }\n",
    "  .metric-card:hover { transform: translateY(-3px); border-color: var(--accent-blue); }\n",
    "  .metric-card .value {\n",
    "    font-size: 2rem; font-weight: 800;\n",
    "    background: linear-gradient(135deg, var(--accent-blue), var(--accent-cyan));\n",
    "    -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n",
    "    line-height: 1.1;\n",
    "  }\n",
    "  .metric-card .label {\n",
    "    font-size: 0.75rem; color: var(--text-muted);\n",
    "    margin-top: 4px; text-transform: uppercase; letter-spacing: 1px;\n",
    "  }\n",
    "\n",
    "  .rec-card {\n",
    "    background: var(--bg-card2);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: var(--radius);\n",
    "    padding: 1rem 1.25rem;\n",
    "    margin-bottom: 0.75rem;\n",
    "    display: flex; align-items: center; gap: 1rem;\n",
    "    transition: all 0.2s;\n",
    "  }\n",
    "  .rec-card:hover { border-color: var(--accent-blue); transform: translateX(4px); }\n",
    "  .rec-rank { font-size: 1.5rem; font-weight: 800; color: var(--accent-blue); min-width: 36px; }\n",
    "  .rec-title { font-size: 1rem; font-weight: 600; color: var(--text-primary); }\n",
    "  .rec-meta  { font-size: 0.8rem; color: var(--text-muted); }\n",
    "  .score-badge {\n",
    "    margin-left: auto; padding: 4px 12px; border-radius: 20px;\n",
    "    font-size: 0.8rem; font-weight: 700;\n",
    "    background: linear-gradient(135deg,\n",
    "      rgba(108,99,255,0.2), rgba(72,202,228,0.2));\n",
    "    border: 1px solid rgba(108,99,255,0.4);\n",
    "    color: var(--accent-cyan); white-space: nowrap;\n",
    "  }\n",
    "\n",
    "  .section-header {\n",
    "    font-size: 1.4rem; font-weight: 700;\n",
    "    color: var(--text-primary);\n",
    "    border-left: 4px solid var(--accent-blue);\n",
    "    padding-left: 1rem; margin: 2rem 0 1rem 0;\n",
    "  }\n",
    "\n",
    "  .algo-pill {\n",
    "    display: inline-block; padding: 4px 16px;\n",
    "    border-radius: 20px; font-size: 0.78rem; font-weight: 600;\n",
    "    margin-right: 6px;\n",
    "  }\n",
    "  .pill-cb { background: rgba(108,99,255,0.15);\n",
    "             border: 1px solid rgba(108,99,255,0.4); color: #A78BFA; }\n",
    "  .pill-cf { background: rgba(255,107,157,0.15);\n",
    "             border: 1px solid rgba(255,107,157,0.4); color: #FF6B9D; }\n",
    "  .pill-hybrid { background: rgba(6,214,160,0.15);\n",
    "                 border: 1px solid rgba(6,214,160,0.4); color: #06D6A0; }\n",
    "\n",
    "  .stSelectbox > div > div {\n",
    "    background: var(--bg-card2) !important;\n",
    "    border-color: var(--border) !important;\n",
    "  }\n",
    "  .stTabs [data-baseweb=\"tab-list\"] {\n",
    "    background: var(--bg-card) !important;\n",
    "    border-radius: var(--radius) !important;\n",
    "  }\n",
    "  .stTabs [data-baseweb=\"tab\"]     { color: var(--text-muted) !important; }\n",
    "  .stTabs [aria-selected=\"true\"]   { color: var(--accent-blue) !important; }\n",
    "\n",
    "  .stButton > button {\n",
    "    background: linear-gradient(135deg,\n",
    "      var(--accent-blue), #8B5CF6) !important;\n",
    "    color: white !important; border: none !important;\n",
    "    border-radius: 8px !important; font-weight: 600 !important;\n",
    "    padding: 0.6rem 2rem !important;\n",
    "  }\n",
    "  .stButton > button:hover {\n",
    "    transform: translateY(-2px);\n",
    "    box-shadow: 0 8px 24px rgba(108,99,255,0.4) !important;\n",
    "  }\n",
    "\n",
    "  div[data-testid=\"stSidebar\"] {\n",
    "    background: var(--bg-card) !important;\n",
    "    border-right: 1px solid var(--border) !important;\n",
    "  }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  DATA + MODEL LOADING (cached)\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "@st.cache_resource(show_spinner=\"🤖 Training recommendation models…\")\n",
    "def load_and_train():\n",
    "    movies, ratings                  = load_movielens_data()\n",
    "    movies_f, ratings_f, rm, sm      = preprocess_data(movies, ratings)\n",
    "    cb      = ContentBasedRecommender().fit(movies_f)\n",
    "    cf      = CollaborativeFilteringRecommender(method='item-item').fit(rm, movies_f)\n",
    "    hybrid  = HybridRecommender(alpha=0.5).fit(movies_f, rm)\n",
    "    metrics = evaluate_model(rm)\n",
    "    return movies_f, ratings_f, rm, cb, cf, hybrid, metrics\n",
    "\n",
    "\n",
    "movies, ratings, rating_matrix, cb_model, cf_model, hybrid_model, metrics = load_and_train()\n",
    "all_titles = sorted(movies['title'].unique().tolist())\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  SIDEBAR\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "with st.sidebar:\n",
    "    st.markdown(\"### ⚙️ Settings\")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    n_recommendations = st.slider(\n",
    "        \"📋 Number of Recommendations\", 5, 20, 10\n",
    "    )\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"### 🧠 Algorithm Info\")\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='font-size:0.85rem; color:#9090B0; line-height:1.8'>\n",
    "    <b style='color:#A78BFA'>Content-Based</b><br>\n",
    "    Genres se similar movies dhundta hai.<br><br>\n",
    "    <b style='color:#FF6B9D'>Collaborative</b><br>\n",
    "    User ratings se similar movies dhundta hai.<br><br>\n",
    "    <b style='color:#06D6A0'>Hybrid</b><br>\n",
    "    Dono ka combination — best results!\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"### 📊 Dataset Info\")\n",
    "    st.markdown(f\"\"\"\n",
    "    <div style='font-size:0.85rem; color:#9090B0; line-height:1.8'>\n",
    "    🎬 Movies : <b style='color:#E8E8FF'>{len(movies):,}</b><br>\n",
    "    👥 Users  : <b style='color:#E8E8FF'>{len(rating_matrix):,}</b><br>\n",
    "    ⭐ Ratings: <b style='color:#E8E8FF'>{len(ratings):,}</b><br>\n",
    "    📐 Matrix : <b style='color:#E8E8FF'>\n",
    "      {rating_matrix.shape[0]}×{rating_matrix.shape[1]}</b>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='font-size:0.75rem; color:#555; text-align:center'>\n",
    "    MSc Data Science Project<br>\n",
    "    Product Recommendation System<br>\n",
    "    <b>Python • Scikit-Learn • Streamlit</b>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  MAIN CONTENT\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<div class='hero-header'>\n",
    "  <div class='hero-title'>🎬 RecoAI</div>\n",
    "  <p style='font-size:1.2rem; color:#C0C0E0; margin:0.5rem 0'>\n",
    "    Intelligent Product Recommendation System\n",
    "  </p>\n",
    "  <p class='hero-subtitle'>\n",
    "    Content-Based &nbsp;•&nbsp; Collaborative Filtering\n",
    "    &nbsp;•&nbsp; Hybrid Model &nbsp;•&nbsp; Real-time Recommendations\n",
    "  </p>\n",
    "</div>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ── Quick Stats ───────────────────────────────\n",
    "sparsity = (rating_matrix == 0).sum().sum() / rating_matrix.size * 100\n",
    "avg_rat  = ratings['rating'].mean()\n",
    "\n",
    "st.markdown(f\"\"\"\n",
    "<div class='metric-row'>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{len(movies):,}</div>\n",
    "    <div class='label'>🎬 Movies</div>\n",
    "  </div>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{len(rating_matrix):,}</div>\n",
    "    <div class='label'>👥 Users</div>\n",
    "  </div>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{len(ratings):,}</div>\n",
    "    <div class='label'>⭐ Ratings</div>\n",
    "  </div>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{avg_rat:.2f}</div>\n",
    "    <div class='label'>📈 Avg Rating</div>\n",
    "  </div>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{sparsity:.0f}%</div>\n",
    "    <div class='label'>🕳️ Sparsity</div>\n",
    "  </div>\n",
    "  <div class='metric-card'>\n",
    "    <div class='value'>{metrics.get('RMSE', 0):.3f}</div>\n",
    "    <div class='label'>🎯 RMSE</div>\n",
    "  </div>\n",
    "</div>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ── Tabs ──────────────────────────────────────\n",
    "tab1, tab2, tab3, tab4 = st.tabs([\n",
    "    \"🔍 Get Recommendations\",\n",
    "    \"📊 Data Analysis\",\n",
    "    \"📈 Model Evaluation\",\n",
    "    \"💡 How It Works\"\n",
    "])\n",
    "\n",
    "\n",
    "# ╔══════════════════════════╗\n",
    "# ║  TAB 1 : RECOMMENDATIONS ║\n",
    "# ╚══════════════════════════╝\n",
    "with tab1:\n",
    "    st.markdown(\n",
    "        \"<div class='section-header'>🎯 Find Similar Movies</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    col_select, col_info = st.columns([2, 1])\n",
    "\n",
    "    with col_select:\n",
    "        selected_movie = st.selectbox(\n",
    "            \"🎬 Select a Movie / Product:\",\n",
    "            all_titles, index=0\n",
    "        )\n",
    "\n",
    "    with col_info:\n",
    "        movie_info = movies[movies['title'] == selected_movie].iloc[0]\n",
    "        st.markdown(f\"\"\"\n",
    "        <div style='background:var(--bg-card2);\n",
    "             border:1px solid var(--border);\n",
    "             border-radius:10px; padding:1rem; margin-top:1.5rem'>\n",
    "          <b>📌 {movie_info['title'][:35]}</b><br>\n",
    "          <span style='color:var(--text-muted); font-size:0.85rem'>\n",
    "            🏷️ {movie_info['genres']}<br>\n",
    "            📅 Year: {movie_info.get('year', 'N/A')}<br>\n",
    "            ⭐ Avg Rating: {movie_info.get('avg_rating', 'N/A')}\n",
    "          </span>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    if st.button(\"🚀 Generate Recommendations\", use_container_width=True):\n",
    "\n",
    "        with st.spinner(\"🔮 Finding best matches…\"):\n",
    "            cb_recs     = cb_model.recommend(selected_movie, n=n_recommendations)\n",
    "            cf_recs     = cf_model.recommend(selected_movie, n=n_recommendations)\n",
    "            hybrid_recs = hybrid_model.recommend(selected_movie, n=n_recommendations)\n",
    "\n",
    "        rec_tab1, rec_tab2, rec_tab3 = st.tabs([\n",
    "            \"🟣 Content-Based\",\n",
    "            \"🔴 Collaborative\",\n",
    "            \"🟢 Hybrid (Best)\"\n",
    "        ])\n",
    "\n",
    "        def render_rec_cards(df, score_col='similarity_score'):\n",
    "            if df is None or df.empty or 'error' in df.columns:\n",
    "                st.warning(\"No recommendations found.\")\n",
    "                return\n",
    "            for i, row in df.iterrows():\n",
    "                genres_str = str(row.get('genres', 'N/A'))[:50]\n",
    "                score      = row.get(score_col,\n",
    "                             row.get('hybrid_score', 0))\n",
    "                score_val  = f\"{score:.4f}\" if pd.notna(score) else \"N/A\"\n",
    "                st.markdown(f\"\"\"\n",
    "                <div class='rec-card'>\n",
    "                  <div class='rec-rank'>#{i+1}</div>\n",
    "                  <div>\n",
    "                    <div class='rec-title'>{row['title']}</div>\n",
    "                    <div class='rec-meta'>\n",
    "                      🏷️ {genres_str} &nbsp;|&nbsp;\n",
    "                      📅 {row.get('year','N/A')} &nbsp;|&nbsp;\n",
    "                      ⭐ {row.get('avg_rating','N/A')}\n",
    "                    </div>\n",
    "                  </div>\n",
    "                  <div class='score-badge'>Score: {score_val}</div>\n",
    "                </div>\n",
    "                \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "        with rec_tab1:\n",
    "            st.markdown(\n",
    "                \"<span class='algo-pill pill-cb'>TF-IDF + Cosine Similarity</span>\"\n",
    "                \" Based on genres & content features\",\n",
    "                unsafe_allow_html=True\n",
    "            )\n",
    "            render_rec_cards(cb_recs)\n",
    "\n",
    "        with rec_tab2:\n",
    "            st.markdown(\n",
    "                \"<span class='algo-pill pill-cf'>User-Item Interaction Matrix</span>\"\n",
    "                \" Based on rating patterns\",\n",
    "                unsafe_allow_html=True\n",
    "            )\n",
    "            render_rec_cards(cf_recs)\n",
    "\n",
    "        with rec_tab3:\n",
    "            st.markdown(\n",
    "                \"<span class='algo-pill pill-hybrid'>α=0.5 Weighted Blend</span>\"\n",
    "                \" Best of both worlds!\",\n",
    "                unsafe_allow_html=True\n",
    "            )\n",
    "            score_col = ('hybrid_score'\n",
    "                         if 'hybrid_score' in hybrid_recs.columns\n",
    "                         else 'similarity_score')\n",
    "            render_rec_cards(hybrid_recs, score_col=score_col)\n",
    "\n",
    "        st.markdown(\n",
    "            \"<div class='section-header'>📊 Visual Comparison</div>\",\n",
    "            unsafe_allow_html=True\n",
    "        )\n",
    "        fig = plot_recommendation_comparison(cb_recs, cf_recs, selected_movie)\n",
    "        st.pyplot(fig, use_container_width=True)\n",
    "        plt.close()\n",
    "\n",
    "\n",
    "# ╔══════════════════════════╗\n",
    "# ║  TAB 2 : DATA ANALYSIS   ║\n",
    "# ╚══════════════════════════╝\n",
    "with tab2:\n",
    "    st.markdown(\n",
    "        \"<div class='section-header'>📊 Exploratory Data Analysis</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    viz_col1, viz_col2 = st.columns(2)\n",
    "\n",
    "    with viz_col1:\n",
    "        st.markdown(\"**⭐ Rating Distribution**\")\n",
    "        fig_r = plot_rating_distribution(ratings)\n",
    "        st.pyplot(fig_r, use_container_width=True)\n",
    "        plt.close()\n",
    "\n",
    "    with viz_col2:\n",
    "        st.markdown(\"**🎬 Genre Analysis**\")\n",
    "        fig_g = plot_genre_analysis(movies)\n",
    "        st.pyplot(fig_g, use_container_width=True)\n",
    "        plt.close()\n",
    "\n",
    "    st.markdown(\"**🌟 Popularity vs Average Rating**\")\n",
    "    fig_p = plot_popularity_vs_ratings(movies)\n",
    "    st.pyplot(fig_p, use_container_width=True)\n",
    "    plt.close()\n",
    "\n",
    "    st.markdown(\"**🔥 Content Similarity Heatmap (Top 20 Movies)**\")\n",
    "    sim_matrix = cb_model.get_similarity_matrix_subset(n=20)\n",
    "    fig_h = plot_similarity_heatmap(sim_matrix, \"Content-Based Cosine Similarity\")\n",
    "    st.pyplot(fig_h, use_container_width=True)\n",
    "    plt.close()\n",
    "\n",
    "    st.markdown(\n",
    "        \"<div class='section-header'>📋 Dataset Preview</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "    tab_m, tab_r = st.tabs([\"Movies Dataset\", \"Ratings Dataset\"])\n",
    "    with tab_m:\n",
    "        st.dataframe(movies.head(50), use_container_width=True)\n",
    "    with tab_r:\n",
    "        st.dataframe(ratings.head(100), use_container_width=True)\n",
    "\n",
    "\n",
    "# ╔══════════════════════════╗\n",
    "# ║  TAB 3 : EVALUATION      ║\n",
    "# ╚══════════════════════════╝\n",
    "with tab3:\n",
    "    st.markdown(\n",
    "        \"<div class='section-header'>📈 Model Performance Metrics</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    fig_ev = plot_evaluation_metrics(metrics)\n",
    "    st.pyplot(fig_ev, use_container_width=True)\n",
    "    plt.close()\n",
    "\n",
    "    mc1, mc2, mc3, mc4 = st.columns(4)\n",
    "    for col, label, val, help_text in [\n",
    "        (mc1, \"RMSE\",        metrics.get('RMSE', 0),\n",
    "               \"Root Mean Square Error — Lower is Better\"),\n",
    "        (mc2, \"MAE\",         metrics.get('MAE', 0),\n",
    "               \"Mean Absolute Error — Lower is Better\"),\n",
    "        (mc3, \"Precision@K\", metrics.get('Precision@K', 0),\n",
    "               \"Precision at K — Higher is Better\"),\n",
    "        (mc4, \"Train Users\", metrics.get('Train_Users', 0),\n",
    "               \"Users used for training\"),\n",
    "    ]:\n",
    "        col.metric(\n",
    "            label = label,\n",
    "            value = f\"{val:.4f}\" if isinstance(val, float) else val,\n",
    "            help  = help_text\n",
    "        )\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='background:var(--bg-card2);\n",
    "         border:1px solid var(--border);\n",
    "         border-radius:12px; padding:1.5rem'>\n",
    "      <h4>📖 Metrics Samjho (Simple)</h4>\n",
    "      <table style='width:100%; border-collapse:collapse; font-size:0.9rem'>\n",
    "        <tr style='border-bottom:1px solid var(--border)'>\n",
    "          <td style='padding:8px; color:#48CAE4; font-weight:600'>RMSE</td>\n",
    "          <td style='padding:8px'>Predicted vs Actual rating ka average error.\n",
    "            0.85 means ~0.85 stars off on average.</td>\n",
    "        </tr>\n",
    "        <tr style='border-bottom:1px solid var(--border)'>\n",
    "          <td style='padding:8px; color:#FF6B9D; font-weight:600'>MAE</td>\n",
    "          <td style='padding:8px'>Mean Absolute Error —\n",
    "            RMSE se thoda simple metric hai.</td>\n",
    "        </tr>\n",
    "        <tr>\n",
    "          <td style='padding:8px; color:#06D6A0; font-weight:600'>Precision@K</td>\n",
    "          <td style='padding:8px'>Top-K recommendations mein kitne relevant the.\n",
    "            0.72 = 72% relevant results.</td>\n",
    "        </tr>\n",
    "      </table>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "# ╔══════════════════════════╗\n",
    "# ║  TAB 4 : HOW IT WORKS    ║\n",
    "# ╚══════════════════════════╝\n",
    "with tab4:\n",
    "    st.markdown(\n",
    "        \"<div class='section-header'>💡 System Architecture</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='background:var(--bg-card2);\n",
    "         border:1px solid var(--border);\n",
    "         border-radius:12px; padding:2rem; line-height:2'>\n",
    "\n",
    "      <h3>🇮🇳 Simple Hinglish Explanation</h3>\n",
    "      <p>Recommendation system ek aisa <b>AI system</b> hai jo batata hai:\n",
    "         <em>\"Tumhe ye bhi pasand aayega!\"</em></p>\n",
    "\n",
    "      <hr style='border-color:var(--border)'>\n",
    "\n",
    "      <h4>🟣 1. Content-Based Filtering</h4>\n",
    "      <p><b>Kya karta hai:</b> Movie ke features (genres) dekho aur\n",
    "         similar features wali movies dhundo.<br>\n",
    "         <b>Example:</b> \"Inception\" (Sci-Fi + Thriller) →\n",
    "         System \"Interstellar\", \"The Matrix\" suggest karega.<br>\n",
    "         <b>Algorithm:</b> TF-IDF → Cosine Similarity</p>\n",
    "\n",
    "      <hr style='border-color:var(--border)'>\n",
    "\n",
    "      <h4>🔴 2. Collaborative Filtering (Item-Item)</h4>\n",
    "      <p><b>Kya karta hai:</b>\n",
    "         \"Jo logon ne ye movies ek saath rate ki, wo similar hain\"<br>\n",
    "         <b>Example:</b> Amazon ka \"Customers who bought X also bought Y\"<br>\n",
    "         <b>Algorithm:</b> Rating Matrix → Item-Item Cosine Similarity</p>\n",
    "\n",
    "      <hr style='border-color:var(--border)'>\n",
    "\n",
    "      <h4>🟢 3. Hybrid System</h4>\n",
    "      <p><b>Formula:</b>\n",
    "         <code>score = 0.5 × content_score + 0.5 × collab_score</code><br>\n",
    "         <b>Used by:</b> Netflix, Spotify, Amazon — sabhi hybrid use karte hain!</p>\n",
    "\n",
    "      <hr style='border-color:var(--border)'>\n",
    "\n",
    "      <h4>📐 Cosine Similarity Formula</h4>\n",
    "      <p><code>similarity = (A · B) / (||A|| × ||B||)</code><br>\n",
    "         <b>Range:</b> 0 (different) se 1 (same)</p>\n",
    "\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='margin-top:1.5rem; background:var(--bg-card2);\n",
    "         border:1px solid #06D6A050;\n",
    "         border-radius:12px; padding:1.5rem'>\n",
    "      <h4>🗂️ Project Structure</h4>\n",
    "      <pre style='color:#06D6A0; font-size:0.85rem; line-height:1.8'>\n",
    "recommendation_system/\n",
    "├── app.py                ← Streamlit web app\n",
    "├── requirements.txt      ← Python packages\n",
    "├── README.md             ← Documentation\n",
    "├── data/                 ← Dataset folder\n",
    "├── models/\n",
    "│   └── recommender.py    ← Core ML algorithms\n",
    "├── utils/\n",
    "│   └── visualizations.py ← Charts & graphs\n",
    "├── notebooks/            ← Jupyter notebooks\n",
    "└── tests/\n",
    "    └── test_recommender.py</pre>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6abf3a4c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
