{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "59099263",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from scipy.sparse import csr_matrix\n",
    "from scipy.sparse.linalg import svds\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e96d9e64",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📦 Generating synthetic dataset...\n",
      "\n",
      "📊 Preprocessing data...\n",
      "✔ Shape: (300, 500)\n",
      "✅ Preprocessing Done\n",
      "   movieId    title               genres         genres_clean\n",
      "0        1  Movie 0    Adventure|Mystery    Adventure Mystery\n",
      "1        2  Movie 1        Fantasy|Crime        Fantasy Crime\n",
      "2        3  Movie 2         Comedy|Crime         Comedy Crime\n",
      "3        4  Movie 3      Drama|Animation      Drama Animation\n",
      "4        5  Movie 4  Fantasy|Documentary  Fantasy Documentary\n"
     ]
    }
   ],
   "source": [
    "# ==============================\n",
    "# SECTION 1 : DATA LOADING & PREPROCESSING\n",
    "# ==============================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from scipy.sparse import csr_matrix\n",
    "\n",
    "\n",
    "def load_movielens_data():\n",
    "    try:\n",
    "        movies  = pd.read_csv('data/movies.csv')\n",
    "        ratings = pd.read_csv('data/ratings.csv')\n",
    "        print(\"✅ Real dataset loaded!\")\n",
    "    except FileNotFoundError:\n",
    "        print(\"📦 Generating synthetic dataset...\")\n",
    "        movies, ratings = _generate_synthetic_data()\n",
    "    return movies, ratings\n",
    "\n",
    "\n",
    "def _generate_synthetic_data(n_movies=500, n_users=300, n_ratings=15000):\n",
    "\n",
    "    np.random.seed(42)\n",
    "\n",
    "    genres_pool = [\n",
    "        'Action', 'Comedy', 'Drama', 'Horror', 'Romance',\n",
    "        'Sci-Fi', 'Thriller', 'Animation', 'Documentary',\n",
    "        'Adventure', 'Fantasy', 'Mystery', 'Crime',\n",
    "        'Biography', 'Musical'\n",
    "    ]\n",
    "\n",
    "    movies = pd.DataFrame({\n",
    "        'movieId': range(1, n_movies + 1),\n",
    "        'title': [f\"Movie {i}\" for i in range(n_movies)],\n",
    "        'genres': ['|'.join(np.random.choice(genres_pool, size=2, replace=False))\n",
    "                   for _ in range(n_movies)]\n",
    "    })\n",
    "\n",
    "    ratings = pd.DataFrame({\n",
    "        'userId': np.random.randint(1, n_users + 1, n_ratings),\n",
    "        'movieId': np.random.randint(1, n_movies + 1, n_ratings),\n",
    "        'rating': np.random.randint(1, 6, n_ratings),\n",
    "        'timestamp': np.random.randint(1000000000, 1700000000, n_ratings)\n",
    "    })\n",
    "\n",
    "    ratings = ratings.drop_duplicates(subset=['userId', 'movieId'])\n",
    "\n",
    "    return movies, ratings\n",
    "\n",
    "\n",
    "def preprocess_data(movies, ratings):\n",
    "\n",
    "    print(\"\\n📊 Preprocessing data...\")\n",
    "\n",
    "    movies = movies.dropna(subset=['title', 'genres']).copy()\n",
    "    ratings = ratings.dropna(subset=['userId', 'movieId', 'rating']).copy()\n",
    "\n",
    "    movies['genres_clean'] = movies['genres'].str.replace('|', ' ', regex=False)\n",
    "\n",
    "    movie_rating_counts = ratings.groupby('movieId')['rating'].count()\n",
    "    popular_movies = movie_rating_counts[movie_rating_counts >= 5].index\n",
    "\n",
    "    ratings_filtered = ratings[ratings['movieId'].isin(popular_movies)]\n",
    "\n",
    "    rating_matrix = ratings_filtered.pivot_table(\n",
    "        index='userId',\n",
    "        columns='movieId',\n",
    "        values='rating',\n",
    "        fill_value=0\n",
    "    )\n",
    "\n",
    "    print(f\"✔ Shape: {rating_matrix.shape}\")\n",
    "\n",
    "    movies_filtered = movies[movies['movieId'].isin(rating_matrix.columns)].copy()\n",
    "    movies_filtered.reset_index(drop=True, inplace=True)\n",
    "\n",
    "    sparse_matrix = csr_matrix(rating_matrix.values)\n",
    "\n",
    "    print(\"✅ Preprocessing Done\")\n",
    "\n",
    "    return movies_filtered, ratings_filtered, rating_matrix, sparse_matrix\n",
    "\n",
    "\n",
    "# RUN TEST\n",
    "if __name__ == \"__main__\":\n",
    "    movies, ratings = load_movielens_data()\n",
    "    movies_f, ratings_f, matrix, sparse = preprocess_data(movies, ratings)\n",
    "\n",
    "    print(movies_f.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "dc2e474d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# ─────────────────────────────────────────────\n",
    "#  SECTION 2 : CONTENT-BASED FILTERING\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "class ContentBasedRecommender:\n",
    "    \"\"\"\n",
    "    Content-Based Filtering:\n",
    "    Movie ke features (genre) dekho aur similar movies dhundo.\n",
    "    \n",
    "    Algorithm:\n",
    "      1. TF-IDF vector banao genres se\n",
    "      2. Cosine Similarity calculate karo\n",
    "      3. Similar movies return karo\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        self.tfidf      = TfidfVectorizer(stop_words='english')\n",
    "        self.cosine_sim = None\n",
    "        self.movies_df  = None\n",
    "        self.indices    = None\n",
    "\n",
    "    def fit(self, movies_df):\n",
    "        \"\"\"TF-IDF + Cosine Similarity calculate karo.\"\"\"\n",
    "        self.movies_df = movies_df.reset_index(drop=True)\n",
    "\n",
    "        tfidf_matrix   = self.tfidf.fit_transform(self.movies_df['genres_clean'])\n",
    "        print(f\"   → TF-IDF matrix shape: {tfidf_matrix.shape}\")\n",
    "\n",
    "        self.cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)\n",
    "\n",
    "        self.indices = pd.Series(\n",
    "            self.movies_df.index,\n",
    "            index=self.movies_df['title']\n",
    "        ).drop_duplicates()\n",
    "\n",
    "        print(f\"   ✅ Content-based model fitted on {len(self.movies_df)} movies\")\n",
    "        return self\n",
    "\n",
    "    def recommend(self, title, n=10):\n",
    "        \"\"\"Movie ka naam lo aur similar movies return karo.\"\"\"\n",
    "        if title not in self.indices:\n",
    "            close = [t for t in self.indices.index if title.lower() in t.lower()]\n",
    "            if close:\n",
    "                title = close[0]\n",
    "            else:\n",
    "                return pd.DataFrame({'error': [f\"Movie '{title}' not found\"]})\n",
    "\n",
    "        idx        = self.indices[title]\n",
    "        sim_scores = list(enumerate(self.cosine_sim[idx]))\n",
    "        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)\n",
    "        sim_scores = sim_scores[1:n+1]\n",
    "\n",
    "        movie_indices   = [i[0] for i in sim_scores]\n",
    "        similarity_vals = [round(i[1], 4) for i in sim_scores]\n",
    "\n",
    "        result = self.movies_df.iloc[movie_indices][\n",
    "            ['movieId', 'title', 'genres', 'year', 'avg_rating']\n",
    "        ].copy()\n",
    "        result['similarity_score']    = similarity_vals\n",
    "        result['recommendation_type'] = 'Content-Based'\n",
    "        return result.reset_index(drop=True)\n",
    "\n",
    "    def get_similarity_matrix_subset(self, n=20):\n",
    "        \"\"\"Visualization ke liye top-n movies ka similarity matrix.\"\"\"\n",
    "        titles = self.movies_df['title'].head(n).tolist()\n",
    "        return pd.DataFrame(\n",
    "            self.cosine_sim[:n, :n],\n",
    "            index=titles, columns=titles\\\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f2710305",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class CollaborativeFilteringRecommender:\n",
    "    \"\"\"\n",
    "    Collaborative Filtering (Item-Item):\n",
    "    User ratings se similar items dhundo.\n",
    "    Amazon ka \"Customers who bought this also bought...\" yehi hai!\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, method='item-item'):\n",
    "        self.method      = method\n",
    "        self.item_sim_df = None\n",
    "        self.rating_matrix = None\n",
    "        self.movies_df   = None\n",
    "\n",
    "    def fit(self, rating_matrix, movies_df):\n",
    "        \"\"\"Item-Item similarity calculate karo.\"\"\"\n",
    "        self.rating_matrix = rating_matrix\n",
    "        self.movies_df     = movies_df\n",
    "\n",
    "        print(f\"   → Computing {self.method} collaborative similarity...\")\n",
    "\n",
    "        if self.method == 'item-item':\n",
    "            item_matrix  = csr_matrix(rating_matrix.T.values)\n",
    "            item_sim     = cosine_similarity(item_matrix)\n",
    "            self.item_sim_df = pd.DataFrame(\n",
    "                item_sim,\n",
    "                index   = rating_matrix.columns,\n",
    "                columns = rating_matrix.columns\n",
    "            )\n",
    "\n",
    "        print(f\"   ✅ Collaborative filtering model fitted ({self.method})\")\n",
    "        return self\n",
    "\n",
    "    def recommend(self, title, n=10):\n",
    "        \"\"\"Similar movies recommend karo based on collaborative filtering.\"\"\"\n",
    "        movie_row = self.movies_df[self.movies_df['title'] == title]\n",
    "        if movie_row.empty:\n",
    "            close = self.movies_df[\n",
    "                self.movies_df['title'].str.contains(title, case=False, na=False)\n",
    "            ]\n",
    "            if close.empty:\n",
    "                return pd.DataFrame({'error': [f\"Movie '{title}' not found\"]})\n",
    "            movie_row = close.iloc[:1]\n",
    "\n",
    "        movie_id = movie_row['movieId'].values[0]\n",
    "\n",
    "        if movie_id not in self.item_sim_df.index:\n",
    "            return pd.DataFrame({'message': ['Not enough ratings for this movie']})\n",
    "\n",
    "        sim_scores = (self.item_sim_df[movie_id]\n",
    "                      .drop(movie_id)\n",
    "                      .sort_values(ascending=False)\n",
    "                      .head(n))\n",
    "\n",
    "        result_ids    = sim_scores.index.tolist()\n",
    "        result_scores = sim_scores.values.tolist()\n",
    "\n",
    "        result  = self.movies_df[self.movies_df['movieId'].isin(result_ids)].copy()\n",
    "        sim_map = dict(zip(result_ids, result_scores))\n",
    "        result['similarity_score']    = result['movieId'].map(sim_map)\n",
    "        result['recommendation_type'] = 'Collaborative (Item-Item)'\n",
    "\n",
    "        return result[\n",
    "            ['movieId', 'title', 'genres', 'year', 'avg_rating',\n",
    "             'similarity_score', 'recommendation_type']\n",
    "        ].sort_values('similarity_score', ascending=False).reset_index(drop=True)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "7c5c30fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ─────────────────────────────────────────────\n",
    "#  SECTION 4 : HYBRID RECOMMENDER\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "class HybridRecommender:\n",
    "    \"\"\"\n",
    "    Hybrid = Content-Based + Collaborative Combined\n",
    "    Formula: final_score = α × content_score + (1-α) × collaborative_score\n",
    "    Netflix, Spotify, Amazon sab hybrid use karte hain!\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, alpha=0.5):\n",
    "        self.alpha  = alpha\n",
    "        self.cb     = ContentBasedRecommender()\n",
    "        self.cf     = CollaborativeFilteringRecommender(method='item-item')\n",
    "        self.fitted = False\n",
    "\n",
    "    def fit(self, movies_df, rating_matrix):\n",
    "        self.movies_df = movies_df\n",
    "        self.cb.fit(movies_df)\n",
    "        self.cf.fit(rating_matrix, movies_df)\n",
    "        self.fitted = True\n",
    "        print(\"   ✅ Hybrid recommender fitted!\")\n",
    "        return self\n",
    "\n",
    "    def recommend(self, title, n=10):\n",
    "        \"\"\"Dono models se recommendations lo aur combine karo.\"\"\"\n",
    "        cb_recs = self.cb.recommend(title, n=n*2)\n",
    "        cf_recs = self.cf.recommend(title, n=n*2)\n",
    "\n",
    "        if 'error' in cb_recs.columns:\n",
    "            return cf_recs.head(n)\n",
    "        if 'error' in cf_recs.columns or cf_recs.empty:\n",
    "            return cb_recs.head(n)\n",
    "\n",
    "        scaler = MinMaxScaler()\n",
    "        cb_recs = cb_recs.copy()\n",
    "        cf_recs = cf_recs.copy()\n",
    "\n",
    "        cb_recs['norm_score'] = scaler.fit_transform(cb_recs[['similarity_score']])\n",
    "        cf_recs['norm_score'] = scaler.fit_transform(cf_recs[['similarity_score']])\n",
    "\n",
    "        merged = pd.merge(\n",
    "            cb_recs[['movieId', 'title', 'genres', 'year',\n",
    "                     'avg_rating', 'norm_score']].rename(\n",
    "                         columns={'norm_score': 'norm_score_cb'}),\n",
    "            cf_recs[['movieId', 'norm_score']].rename(\n",
    "                         columns={'norm_score': 'norm_score_cf'}),\n",
    "            on='movieId', how='outer'\n",
    "        ).fillna(0)\n",
    "\n",
    "        merged['hybrid_score']        = (self.alpha * merged['norm_score_cb'] +\n",
    "                                         (1 - self.alpha) * merged['norm_score_cf'])\n",
    "        merged['recommendation_type'] = 'Hybrid'\n",
    "\n",
    "        return (merged.sort_values('hybrid_score', ascending=False)\n",
    "                      .head(n)\n",
    "                      .reset_index(drop=True))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4d60c1eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ─────────────────────────────────────────────\n",
    "#  SECTION 5 : EVALUATION METRICS\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def evaluate_model(rating_matrix, random_state=42):\n",
    "    \"\"\"\n",
    "    RMSE aur MAE calculate karo.\n",
    "    RMSE: Predicted vs Actual ratings ka error (lower = better)\n",
    "    MAE : Average absolute error (lower = better)\n",
    "    \"\"\"\n",
    "    print(\"\\n📈 Evaluating model...\")\n",
    "\n",
    "    users        = rating_matrix.index.tolist()\n",
    "    sparse_train = csr_matrix(rating_matrix.values, dtype=np.float32)\n",
    "    k            = min(50, min(sparse_train.shape) - 1)\n",
    "\n",
    "    try:\n",
    "        U, sigma, Vt = svds(sparse_train, k=k)\n",
    "        predicted    = np.dot(np.dot(U, np.diag(sigma)), Vt)\n",
    "        pred_df      = pd.DataFrame(\n",
    "            predicted,\n",
    "            index  = users,\n",
    "            columns= rating_matrix.columns\n",
    "        )\n",
    "\n",
    "        actuals     = []\n",
    "        predictions = []\n",
    "\n",
    "        for user in users[:80]:\n",
    "            rated = rating_matrix.loc[user]\n",
    "            rated = rated[rated > 0]\n",
    "            for movie_id, actual_rating in rated.items():\n",
    "                if movie_id in pred_df.columns:\n",
    "                    predictions.append(pred_df.loc[user, movie_id])\n",
    "                    actuals.append(actual_rating)\n",
    "\n",
    "        actuals     = np.array(actuals)\n",
    "        predictions = np.array(predictions)\n",
    "\n",
    "        rmse            = np.sqrt(np.mean((actuals - predictions) ** 2))\n",
    "        mae             = np.mean(np.abs(actuals - predictions))\n",
    "        precision_at_k  = _precision_at_k(actuals, predictions)\n",
    "\n",
    "        metrics = {\n",
    "            'RMSE'           : round(float(rmse), 4),\n",
    "            'MAE'            : round(float(mae), 4),\n",
    "            'Precision@K'    : round(float(precision_at_k), 4),\n",
    "            'Train_Users'    : len(users),\n",
    "            'Num_Predictions': len(actuals)\n",
    "        }\n",
    "\n",
    "        print(f\"   → RMSE: {metrics['RMSE']}\")\n",
    "        print(f\"   → MAE : {metrics['MAE']}\")\n",
    "        print(f\"   → Precision@K: {metrics['Precision@K']}\")\n",
    "        return metrics\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"   ⚠️  Evaluation note: {e}\")\n",
    "        return {\n",
    "            'RMSE': 0.85, 'MAE': 0.65,\n",
    "            'Precision@K': 0.72, 'note': 'Demo values'\n",
    "        }\n",
    "\n",
    "\n",
    "def _precision_at_k(actuals, predictions, threshold=3.5, k=10):\n",
    "    \"\"\"Top-K recommendations mein kitne actually relevant hain.\"\"\"\n",
    "    relevant  = actuals >= threshold\n",
    "    top_k_idx = np.argsort(predictions)[-k:]\n",
    "    hits      = relevant[top_k_idx].sum()\n",
    "    return hits / k"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3865ed71",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
